# Generated by Django 4.1.3 on 2022-11-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contatos',
            new_name='Contato',
        ),
    ]
